### ISSUE TITLE
Breaking change on 4.1.1 from 4.1.0

### ISSUE THREAD

**Issue by dfleury** [mistakster/postcss-pipeline-webpack-plugin#53]
The version 4.1.1 is requiring a `processor` key on the config object. That's ok, however the SemVer prohibit patch releases of introduce breaking changes. 
When I downgrade it to 4.1.0 the error go away.
I just replaced `pipeline` config key name for `processor` and it started to work once again.
```
{omitted}/node_modules/webpack-cli/bin/cli.js:231
                                throw err;
                                ^

Error: You must provide a PostCSS processor instance
    at new PostCssPipelineWebpackPlugin ({omitted}/node_modules/postcss-pipeline-webpack-plugin/lib/postcss-pipeline-webpack-plugin.js:24:11)
    at Object.module.exports.getConfig ({omitted}/src/tools/webpack/postcss/pipeline.js:16:9)
    at generateConfig ({omitted}/src/tools/webpack/postcss/postcss.js:20:19)
    at Object.module.exports.getConfig ({omitted}/src/tools/webpack/postcss/postcss.js:36:10)
    at externalCssExtraction ({omitted}/src/tools/webpack/plugins.js:11:17)
    at getPlugins ({omitted}/src/tools/webpack/plugins.js:57:4)
    at standa...
```

**Comment by mistakster** [comment]
Hi @dfleury! Thank you so much for the report. I’ve just deprecated `v4.1.1` and published `v4.1.2` to fix the issue.

Also, I published a new major version `v5.0.0` which brings the new API. `postcss-pipeline-webpack-plugin` must be configured with an existing PostCSS processor instance. I have to introduce this option to let the developer chose between PostCSS 6.x and PostCSS 7.x

Please, let me know if you face any other issues.
